from __future__ import annotations

from datetime import datetime
import os

from prometheus_client import Counter, Gauge, Histogram, Info

APP_INFO = Info("biosentinel", "Bio Sentinel application metadata")
APP_INFO.info(
    {
        "version": "2.1.0",
        "environment": os.getenv("ENVIRONMENT", "dev"),
        "state": os.getenv("STATE_CODE", "unknown"),
    }
)

REQUEST_COUNT = Counter(
    "biosentinel_http_requests_total",
    "Total HTTP requests",
    ["method", "endpoint", "status", "agent"],
)

REQUEST_DURATION = Histogram(
    "biosentinel_http_request_duration_seconds",
    "HTTP request duration",
    ["method", "endpoint", "agent"],
    buckets=[0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0],
)

AGENT_EXECUTION_COUNT = Counter(
    "biosentinel_agent_executions_total",
    "Agent tool executions",
    ["agent", "tool", "status"],
)

AGENT_EXECUTION_DURATION = Histogram(
    "biosentinel_agent_execution_duration_seconds",
    "Agent execution duration",
    ["agent", "tool"],
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0],
)

INFERENCE_COUNT = Counter(
    "biosentinel_inference_requests_total",
    "Model inference requests",
    ["model", "backend", "language", "status"],
)

INFERENCE_DURATION = Histogram(
    "biosentinel_inference_duration_seconds",
    "Model inference duration",
    ["model", "backend"],
    buckets=[0.5, 1.0, 2.0, 5.0, 10.0, 20.0, 40.0],
)

EXTRACTION_CONFIDENCE = Histogram(
    "biosentinel_extraction_confidence_score",
    "Syndrome extraction confidence scores",
    ["syndrome", "language"],
    buckets=[0.0, 0.2, 0.4, 0.6, 0.8, 0.9, 0.95, 1.0],
)

INTEGRATION_SYNC_COUNT = Counter(
    "biosentinel_integration_sync_total",
    "External system sync attempts",
    ["integration", "operation", "status"],
)

INTEGRATION_QUEUE_SIZE = Gauge(
    "biosentinel_integration_queue_size",
    "Pending items in offline sync queue",
    ["integration"],
)

ENCOUNTERS_BY_SYNDROME = Counter(
    "biosentinel_encounters_by_syndrome_total",
    "Encounters grouped by syndrome",
    ["syndrome", "state", "district", "risk_tier"],
)

ALERTS_GENERATED = Counter(
    "biosentinel_alerts_generated_total",
    "Alerts generated by type",
    ["alert_type", "severity", "escalation_level"],
)

MODEL_MEMORY_USAGE = Gauge(
    "biosentinel_model_memory_bytes",
    "Memory usage by loaded models",
    ["model", "backend"],
)

GPU_UTILIZATION = Gauge(
    "biosentinel_gpu_utilization_percent",
    "GPU utilization percentage",
    ["device_id"],
)


def record_http_request(method: str, endpoint: str, status: str, duration_seconds: float, agent: str = "api") -> None:
    REQUEST_COUNT.labels(method=method, endpoint=endpoint, status=status, agent=agent).inc()
    REQUEST_DURATION.labels(method=method, endpoint=endpoint, agent=agent).observe(duration_seconds)


def record_agent_execution(agent: str, tool: str, status: str, duration_seconds: float) -> None:
    AGENT_EXECUTION_COUNT.labels(agent=agent, tool=tool, status=status).inc()
    AGENT_EXECUTION_DURATION.labels(agent=agent, tool=tool).observe(duration_seconds)


def record_inference(model: str, backend: str, language: str, status: str, duration_seconds: float, confidence: float | None = None, syndrome: str = "unknown") -> None:
    INFERENCE_COUNT.labels(model=model, backend=backend, language=language, status=status).inc()
    INFERENCE_DURATION.labels(model=model, backend=backend).observe(duration_seconds)
    if confidence is not None:
        EXTRACTION_CONFIDENCE.labels(syndrome=syndrome, language=language).observe(confidence)


def set_queue_size(integration: str, size: int) -> None:
    INTEGRATION_QUEUE_SIZE.labels(integration=integration).set(size)


def instrument_agent(agent_name: str, tool_name: str):
    """Decorator to instrument async or sync tool functions."""

    def decorator(func):
        if hasattr(func, "__call__"):
            pass

        async def async_wrapper(*args, **kwargs):
            start = datetime.now().timestamp()
            try:
                result = await func(*args, **kwargs)
                record_agent_execution(agent_name, tool_name, "success", datetime.now().timestamp() - start)
                return result
            except Exception:
                record_agent_execution(agent_name, tool_name, "error", datetime.now().timestamp() - start)
                raise

        def sync_wrapper(*args, **kwargs):
            start = datetime.now().timestamp()
            try:
                result = func(*args, **kwargs)
                record_agent_execution(agent_name, tool_name, "success", datetime.now().timestamp() - start)
                return result
            except Exception:
                record_agent_execution(agent_name, tool_name, "error", datetime.now().timestamp() - start)
                raise

        # Prefer async wrapper if function is coroutine.
        import inspect

        return async_wrapper if inspect.iscoroutinefunction(func) else sync_wrapper

    return decorator


def instrument_inference(model_name: str, backend: str):
    """Decorator to instrument async or sync inference functions."""

    def decorator(func):
        import inspect

        async def async_wrapper(text: str, language: str = "eng", **kwargs):
            start = datetime.now().timestamp()
            try:
                result = await func(text, language, **kwargs)
                record_inference(
                    model=model_name,
                    backend=backend,
                    language=language,
                    status="success",
                    duration_seconds=datetime.now().timestamp() - start,
                    confidence=(result.get("confidence") if isinstance(result, dict) else None),
                    syndrome=(result.get("syndrome", "unknown") if isinstance(result, dict) else "unknown"),
                )
                return result
            except Exception:
                record_inference(
                    model=model_name,
                    backend=backend,
                    language=language,
                    status="error",
                    duration_seconds=datetime.now().timestamp() - start,
                )
                raise

        def sync_wrapper(text: str, language: str = "eng", **kwargs):
            start = datetime.now().timestamp()
            try:
                result = func(text, language, **kwargs)
                record_inference(
                    model=model_name,
                    backend=backend,
                    language=language,
                    status="success",
                    duration_seconds=datetime.now().timestamp() - start,
                    confidence=(result.get("confidence") if isinstance(result, dict) else None),
                    syndrome=(result.get("syndrome", "unknown") if isinstance(result, dict) else "unknown"),
                )
                return result
            except Exception:
                record_inference(
                    model=model_name,
                    backend=backend,
                    language=language,
                    status="error",
                    duration_seconds=datetime.now().timestamp() - start,
                )
                raise

        return async_wrapper if inspect.iscoroutinefunction(func) else sync_wrapper

    return decorator
